<a href="https://colab.research.google.com/github/CansecoSergio/python-data-science/blob/main/M6%20Activate%20PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MÓDULO 6 - INGENIERÍA DE CARACTERÍSTICAS**

---


**TEMA 1. PCA**

#### Instrucciones

1. Revisa la documentación relacionada con los datos que vamos a trabajar y has un breve resumen sobre las variables que tiene el conjunto de datos:

USArrests: https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/USArrests

__Aquí va tu descripción__


2. Importa las paqueterías necesarias para hacer el análisis

In [1]:
# Tratamiento de datos(3 paqueterías: numpy, pandas, statsmodels.api)
# ==============================================================================
import numpy as np
import pandas as pd
import statsmodels.api as sm

# Preprocesado y modelado (3 paqueterías sklearn.decompositio para PCA, StandardScaler, scale)
# ==============================================================================
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale

# Configuración warnings
# ==============================================================================
import warnings
warnings.filterwarnings('ignore')

3. Lee los datos tal cuál en el ejercico anterior, sustituyendo "iris" por "USArrests" (3 sustituciones)

In [3]:
arrests = sm.datasets.get_rdataset('USArrests', 'datasets')
datos = arrests.data
datos

Murder  Assault  UrbanPop  Rape
rownames                                       
Alabama           13.2      236        58  21.2
Alaska            10.0      263        48  44.5
Arizona            8.1      294        80  31.0
Arkansas           8.8      190        50  19.5
California         9.0      276        91  40.6
Colorado           7.9      204        78  38.7
Connecticut        3.3      110        77  11.1
Delaware           5.9      238        72  15.8
Florida           15.4      335        80  31.9
Georgia           17.4      211        60  25.8
Hawaii             5.3       46        83  20.2
Idaho              2.6      120        54  14.2
Illinois          10.4      249        83  24.0
Indiana            7.2      113        65  21.0
Iowa               2.2       56        57  11.3
Kansas             6.0      115        66  18.0
Kentucky           9.7      109        52  16.3
Louisiana         15.4      249        66  22.2
Maine              2.1       83        51   7.8
Maryland          11.3      300        67  27.8
Massachusetts      4.4      149        85  16.3
Michigan          12.1      255        74  35.1
Minnesota          2.7       72        66  14.9
Mississippi       16.1      259        44  17.1
Missouri           9.0      178        70  28.2
Montana            6.0      109        53  16.4
Nebraska           4.3      102        62  16.5
Nevada            12.2      252        81  46.0
New Hampshire      2.1       57        56   9.5
New Jersey         7.4      159        89  18.8
New Mexico        11.4      285        70  32.1
New York          11.1      254        86  26.1
North Carolina    13.0      337        45  16.1
North Dakota       0.8       45        44   7.3
Ohio               7.3      120        75  21.4
Oklahoma           6.6      151        68  20.0
Oregon             4.9      159        67  29.3
Pennsylvania       6.3      106        72  14.9
Rhode Island       3.4      174        87   8.3
South Carolina    14.4      279        48  22.5
South Dakota       3.8       86        45  12.8
Tennessee         13.2      188        59  26.9
Texas             12.7      201        80  25.5
Utah               3.2      120        80  22.9
Vermont            2.2       48        32  11.2
Virginia           8.5      156        63  20.7
Washington         4.0      145        73  26.2
West Virginia      5.7       81        39   9.3
Wisconsin          2.6       53        66  10.8
Wyoming            6.8      161        60  15.6

4. Calcula la media y la desviación estándar de las variables

In [5]:
#Media
datos.mean()

Murder        7.788
Assault     170.760
UrbanPop     65.540
Rape         21.232
dtype: float64

In [6]:
#Desviación estándar
datos.std()

Murder       4.355510
Assault     83.337661
UrbanPop    14.474763
Rape         9.366385
dtype: float64

5. Estandariza tus variables

__¡Importante!__ A diferencia del conjunto de datos de Iris, en este conjunto de datos no tenemos una variable Y definida, por lo tanto, la transformación se hace a las 4 variables en el conjunto de datos y hacer una division entre Y y X no es necesario.

In [7]:
# Utiliza StandarScaler
escalar = StandardScaler()

In [8]:
#Calcula los datos escalados con .fit y .transform
datos_escalados = escalar.fit(datos)
datos_escalados = escalar.transform(datos)
datos_escalados

array([[ 1.25517927,  0.79078716, -0.52619514, -0.00345116],
       [ 0.51301858,  1.11805959, -1.22406668,  2.50942392],
       [ 0.07236067,  1.49381682,  1.00912225,  1.05346626],
       [ 0.23470832,  0.23321191, -1.08449238, -0.18679398],
       [ 0.28109336,  1.2756352 ,  1.77678094,  2.08881393],
       [ 0.02597562,  0.40290872,  0.86954794,  1.88390137],
       [-1.04088037, -0.73648418,  0.79976079, -1.09272319],
       [-0.43787481,  0.81502956,  0.45082502, -0.58583422],
       [ 1.76541475,  1.99078607,  1.00912225,  1.1505301 ],
       [ 2.22926518,  0.48775713, -0.38662083,  0.49265293],
       [-0.57702994, -1.51224105,  1.21848371, -0.11129987],
       [-1.20322802, -0.61527217, -0.80534376, -0.75839217],
       [ 0.60578867,  0.94836277,  1.21848371,  0.29852525],
       [-0.13637203, -0.70012057, -0.03768506, -0.0250209 ],
       [-1.29599811, -1.39102904, -0.5959823 , -1.07115345],
       [-0.41468229, -0.67587817,  0.03210209, -0.34856705],
       [ 0.44344101, -0.

6. Utiliza el modelo de PCA
*  ¿Cuántos componentes debemos de considerar y por qué?
*  Construye el modelo utilizando PCA de sklearn

__Aquí va tu respuesta a la primera pregunta__

In [9]:
#Utiliza PCA con n_components considerando tu pregunta anterior
pca_model = PCA(n_components=4)

In [10]:
#Ajusta tu modelocon la función .fit y tus datos estandarizados
pca_model.fit(datos_escalados)

PCA(n_components=4)

7. Extrae la matriz de cargas de tu modelo construido

In [11]:
#utiliza .components_
pca_model.components_

array([[ 0.53589947,  0.58318363,  0.27819087,  0.54343209],
       [ 0.41818087,  0.1879856 , -0.87280619, -0.16731864],
       [-0.34123273, -0.26814843, -0.37801579,  0.81777791],
       [ 0.6492278 , -0.74340748,  0.13387773,  0.08902432]])

In [13]:
#crea un dataframe más entendible
cargas = pd.DataFrame(
    data    = pca_model.components_,
    columns = datos.columns,
    index   = ['PC1', 'PC2', 'PC3', 'PC4']
)

cargas

Murder   Assault  UrbanPop      Rape
PC1  0.535899  0.583184  0.278191  0.543432
PC2  0.418181  0.187986 -0.872806 -0.167319
PC3 -0.341233 -0.268148 -0.378016  0.817778
PC4  0.649228 -0.743407  0.133878  0.089024

8. Análisa el primer y segundo componente principal con respecto a sus cargas, ¿Qué información describe cada uno?

__Aquí va tu respuesta__

9. Calcula el porcentaje de varianza explicada acumula

In [14]:
# Utiliza .explained_variance_ratio_.cumsum()
varianza_acum = pca_model.explained_variance_ratio_.cumsum()
varianza_acum

array([0.62006039, 0.86750168, 0.95664248, 1.        ])

10. Determina cuántos componentes principales vas a considerar para crear tu nuevo conjunto de datos y ¿por qué?

__Aquí va tu respuesta__

11. Has la última conversión para poder tener tu nuevo conjunto de datos


*   Multiplicación de matriz de cargas por valores originales
*   Asignar nombres de componentes
*   Transponer la matriz para obtener resultado final


In [15]:
#utilizar el ejemplo de proyecciones
proyecciones = np.dot(pca_model.components_, scale(datos).T)
proyecciones = pd.DataFrame(proyecciones, index = ['PC1', 'PC2', 'PC3', 'PC4'])
#print(proyecciones)

proyecciones = proyecciones.transpose().set_index(datos.index)
proyecciones

PC1       PC2       PC3       PC4
rownames                                              
Alabama         0.985566  1.133392 -0.444269  0.156267
Alaska          1.950138  1.073213  2.040003 -0.438583
Arizona         1.763164 -0.745957  0.054781 -0.834653
Arkansas       -0.141420  1.119797  0.114574 -0.182811
California      2.523980 -1.542934  0.598557 -0.341996
Colorado        1.514563 -0.987555  1.095007  0.001465
Connecticut    -1.358647 -1.088928 -0.643258 -0.118469
Delaware        0.047709 -0.325359 -0.718633 -0.881978
Florida         3.013042  0.039229 -0.576829 -0.096285
Georgia         1.639283  1.278942 -0.342460  1.076797
Hawaii         -0.912657 -1.570460  0.050782  0.902807
Idaho          -1.639800  0.210973  0.259801 -0.499104
Illinois        1.378911 -0.681841 -0.677496 -0.122021
Indiana        -0.505461 -0.151563  0.228055  0.424666
Iowa           -2.253646 -0.104054  0.164564  0.017556
Kansas         -0.796881 -0.270165  0.025553  0.206496
Kentucky       -0.750859  0.958440 -0.028369  0.670557
Louisiana       1.564818  0.871055 -0.783480  0.454728
Maine          -2.396829  0.376392 -0.065682 -0.330460
Maryland        1.763369  0.427655 -0.157250 -0.559070
Massachusetts  -0.486166 -1.474496 -0.609497 -0.179599
Michigan        2.108441 -0.155397  0.384869  0.102372
Minnesota      -1.692682 -0.632261  0.153070  0.067317
Mississippi     0.996494  2.393796 -0.740808  0.215508
Missouri        0.696787 -0.263355  0.377444  0.225824
Montana        -1.185452  0.536874  0.246889  0.123742
Nebraska       -1.265637 -0.193954  0.175574  0.015893
Nevada          2.874395 -0.775600  1.163380  0.314515
New Hampshire  -2.383915 -0.018082  0.036855 -0.033137
New Jersey      0.181566 -1.449506 -0.764454  0.243383
New Mexico      1.980024  0.142849  0.183692 -0.339534
New York        1.682577 -0.823184 -0.643075 -0.013484
North Carolina  1.123379  2.228003 -0.863572 -0.954382
North Dakota   -2.992226  0.599119  0.301277 -0.253987
Ohio           -0.225965 -0.742238 -0.031139  0.473916
Oklahoma       -0.311783 -0.287854 -0.015310  0.010332
Oregon          0.059122 -0.541411  0.939833 -0.237781
Pennsylvania   -0.888416 -0.571100 -0.400629  0.359061
Rhode Island   -0.863772 -1.491978 -1.369946 -0.613569
South Carolina  1.320724  1.933405 -0.300538 -0.131467
South Dakota   -1.987775  0.823343  0.389293 -0.109572
Tennessee       0.999742  0.860251  0.188083  0.652864
Texas           1.355138 -0.412481 -0.492069  0.643195
Utah           -0.550565 -1.471505  0.293728 -0.082314
Vermont        -2.801412  1.402288  0.841263 -0.144890
Virginia       -0.096335  0.199735  0.011713  0.211371
Washington     -0.216903 -0.970124  0.624871 -0.220848
West Virginia  -2.108585  1.424847  0.104775  0.131909
Wisconsin      -2.079714 -0.611269 -0.138865  0.184104
Wyoming        -0.629427  0.321013 -0.240659 -0.166652

12. Guarda tu o tus conjuntos de datos finales en drive

*   Llama la paquetería necesaria
*   Crea la conexión
*   Guarda tu archivo en un csv en la carpeta de tu interés

__¡EXCELENTE!__